services:
    culturama-database:
        image: postgres:16.2-alpine3.19
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
        volumes:
            - 'database:/var/lib/postgresql/data'

volumes:
    database:
